version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: despesas-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: despesasdb
      TZ: America/Sao_Paulo
    ports:
      - "5433:5432"   # mapeia porta 5433 no host para 5432 no container
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: despesas-pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8081:80"   # pgAdmin acess√≠vel em http://localhost:8081
    depends_on:
      - postgres

volumes:
  postgres_data: